# Generated by Django 5.1.4 on 2024-12-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='test_files/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='test_files/'),
        ),
    ]
