# Generated by Django 5.1.4 on 2024-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0002_alter_test_answer_file_alter_test_question_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
